# SNMP MIB module (CISCO-UNIFIED-COMPUTING-MIB) expressed in pysnmp data model.
#
# This Python module is designed to be imported and executed by the
# pysnmp library.
#
# See https://www.pysnmp.com/pysnmp for further information.
#
# Notes
# -----
# ASN.1 source file:///Users/lextm/pysnmp.com/mibs.pysnmp.com/asn1/CISCO-UNIFIED-COMPUTING-MIB
# Produced by pysmi-1.5.4 at Mon Oct 14 21:10:00 2024
# On host MacBook-Pro.local platform Darwin version 24.0.0 by user lextm
# Using Python version 3.12.0 (main, Nov 14 2023, 23:52:11) [Clang 15.0.0 (clang-1500.0.40.1)]

if 'mibBuilder' not in globals():
    import sys

    sys.stderr.write(__doc__)
    sys.exit(1)

# Import base ASN.1 objects even if this MIB does not use it

(Integer,
 OctetString,
 ObjectIdentifier) = mibBuilder.importSymbols(
    "ASN1",
    "Integer",
    "OctetString",
    "ObjectIdentifier")

(NamedValues,) = mibBuilder.importSymbols(
    "ASN1-ENUMERATION",
    "NamedValues")
(ConstraintsIntersection,
 SingleValueConstraint,
 ValueRangeConstraint,
 ValueSizeConstraint,
 ConstraintsUnion) = mibBuilder.importSymbols(
    "ASN1-REFINEMENT",
    "ConstraintsIntersection",
    "SingleValueConstraint",
    "ValueRangeConstraint",
    "ValueSizeConstraint",
    "ConstraintsUnion")

# Import SMI symbols from the MIBs this MIB depends on

(ciscoMgmt,) = mibBuilder.importSymbols(
    "CISCO-SMI",
    "ciscoMgmt")

(SnmpAdminString,) = mibBuilder.importSymbols(
    "SNMP-FRAMEWORK-MIB",
    "SnmpAdminString")

(ModuleCompliance,
 NotificationGroup,
 ObjectGroup) = mibBuilder.importSymbols(
    "SNMPv2-CONF",
    "ModuleCompliance",
    "NotificationGroup",
    "ObjectGroup")

(Bits,
 Counter32,
 Counter64,
 Gauge32,
 Integer32,
 IpAddress,
 ModuleIdentity,
 MibIdentifier,
 NotificationType,
 ObjectIdentity,
 MibScalar,
 MibTable,
 MibTableRow,
 MibTableColumn,
 TimeTicks,
 Unsigned32,
 iso) = mibBuilder.importSymbols(
    "SNMPv2-SMI",
    "Bits",
    "Counter32",
    "Counter64",
    "Gauge32",
    "Integer32",
    "IpAddress",
    "ModuleIdentity",
    "MibIdentifier",
    "NotificationType",
    "ObjectIdentity",
    "MibScalar",
    "MibTable",
    "MibTableRow",
    "MibTableColumn",
    "TimeTicks",
    "Unsigned32",
    "iso")

(DateAndTime,
 DisplayString,
 RowPointer,
 TextualConvention) = mibBuilder.importSymbols(
    "SNMPv2-TC",
    "DateAndTime",
    "DisplayString",
    "RowPointer",
    "TextualConvention")


# MODULE-IDENTITY

ciscoUnifiedComputingMIB = ModuleIdentity(
    (1, 3, 6, 1, 4, 1, 9, 9, 719)
)
ciscoUnifiedComputingMIB.setRevisions(
        ("2010-05-20 00:00",)
)


# Types definitions


# TEXTUAL-CONVENTIONS



class CucsManagedObjectId(Unsigned32, TextualConvention):
    status = "current"
    displayHint = "d"


class CucsManagedObjectDn(OctetString, TextualConvention):
    status = "current"


class CucsFaultCode(Integer32, TextualConvention):
    status = "current"
    subtypeSpec = Integer32.subtypeSpec
    subtypeSpec += ConstraintsUnion(
        SingleValueConstraint(
            *(156,
              157,
              169,
              170,
              174,
              175,
              176,
              177,
              178,
              179,
              180,
              182,
              183,
              184,
              185,
              186,
              187,
              188,
              189,
              190,
              191,
              200,
              203,
              206,
              207,
              209,
              276,
              277,
              278,
              279,
              282,
              283,
              291,
              293,
              294,
              304,
              305,
              306,
              310,
              311,
              312,
              313,
              314,
              315,
              317,
              318,
              319,
              320,
              321,
              322,
              324,
              326,
              327,
              329,
              330,
              331,
              332,
              334,
              337,
              367,
              368,
              369,
              371,
              373,
              374,
              376,
              377,
              378,
              379,
              380,
              381,
              382,
              383,
              384,
              385,
              387,
              389,
              391,
              392,
              393,
              394,
              395,
              396,
              397,
              398,
              399,
              400,
              401,
              402,
              403,
              404,
              405,
              406,
              407,
              408,
              409,
              410,
              411,
              424,
              425,
              428,
              429,
              430,
              434,
              435,
              436,
              440,
              451,
              452,
              453,
              454,
              455,
              456,
              458,
              459,
              460,
              461,
              462,
              463,
              464,
              465,
              466,
              470,
              471,
              476,
              478,
              479,
              480,
              481,
              484,
              502,
              517,
              528,
              531,
              532,
              533,
              535,
              536,
              537,
              538,
              539,
              540,
              543,
              549,
              16405,
              16406,
              16407,
              16408,
              16518,
              16519,
              16520,
              16521,
              16522,
              16523,
              16524,
              16525,
              16526,
              16528,
              16529,
              16530,
              16531,
              16532,
              16533,
              16534,
              16535,
              16539,
              16550,
              16576,
              16577,
              16578,
              16579,
              16580,
              16581,
              16600,
              16601,
              16604,
              16605,
              16606,
              16641,
              16650,
              16651,
              16653,
              16654,
              16655,
              16656,
              16657,
              16658,
              16659,
              16670,
              16673,
              16674,
              16679,
              16680,
              16681,
              16682,
              16683,
              16684,
              16739,
              16740,
              16745,
              16750,
              16802,
              16803,
              16815,
              16823,
              16834,
              16852,
              16857,
              16879,
              16880,
              16881,
              16890,
              16891,
              16904,
              16930,
              16931,
              77845,
              77846,
              77847,
              77848,
              77958,
              77959,
              77960,
              77961,
              77962,
              77963,
              77964,
              77965,
              77966,
              77968,
              77969,
              77970,
              77971,
              77972,
              77973,
              77974,
              77975,
              77979,
              77990,
              78016,
              78017,
              78018,
              78019,
              78020,
              78021,
              78040,
              78041,
              78044,
              78045,
              78046,
              78081,
              78090,
              78091,
              78093,
              78094,
              78095,
              78096,
              78097,
              78098,
              78099,
              78110,
              78113,
              78114,
              78119,
              78120,
              78121,
              78122,
              78123,
              78124,
              78179,
              78180,
              78185,
              78190,
              78242,
              78243,
              78255,
              78263,
              78274,
              78292,
              78297,
              78319,
              78320,
              78321,
              78330,
              78331,
              78344,
              78370,
              78371,
              999445,
              999446,
              999447,
              999448,
              999558,
              999559,
              999560,
              999561,
              999562,
              999563,
              999564,
              999565,
              999566,
              999568,
              999569,
              999570,
              999571,
              999572,
              999573,
              999574,
              999575,
              999579,
              999590,
              999616,
              999617,
              999618,
              999619,
              999620,
              999621,
              999640,
              999641,
              999644,
              999645,
              999646,
              999681,
              999690,
              999691,
              999693,
              999694,
              999695,
              999696,
              999697,
              999698,
              999699,
              999710,
              999713,
              999714,
              999719,
              999720,
              999721,
              999722,
              999723,
              999724,
              999779,
              999780,
              999785,
              999790,
              999842,
              999843,
              999855,
              999863,
              999874,
              999892,
              999897,
              999919,
              999920,
              999921,
              999930,
              999931,
              999944,
              999970,
              999971)
        )
    )
    namedValues = NamedValues(
        *(("fltAdaptorExtIfLinkDown", 209),
          ("fltAdaptorHostIfLinkDown", 207),
          ("fltAdaptorUnitAdaptorReachability", 206),
          ("fltAdaptorUnitMissing", 203),
          ("fltAdaptorUnitUnidentifiableFru", 200),
          ("fltComputeBladeAssignedInaccessible", 322),
          ("fltComputeBladeAssignedMissing", 319),
          ("fltComputeBladeAssociationFailed", 315),
          ("fltComputeBladeBiosPostTimeout", 313),
          ("fltComputeBladeDiscoveryFailed", 314),
          ("fltComputeBladeIdentityUnestablishable", 306),
          ("fltComputeBladeInoperable", 317),
          ("fltComputeBladeInsufficientlyEquipped", 305),
          ("fltComputeBladePostFailure", 517),
          ("fltComputeBladePowerProblem", 311),
          ("fltComputeBladeThermalProblem", 312),
          ("fltComputeBladeUnassignedInaccessible", 321),
          ("fltComputeBladeUnassignedMissing", 318),
          ("fltComputeBladeUnidentified", 320),
          ("fltComputeBoardCmosVoltageThresholdCritical", 424),
          ("fltComputeBoardCmosVoltageThresholdNonRecoverable", 425),
          ("fltComputeBoardPowerError", 310),
          ("fltComputeIOHubThermalNonCritical", 538),
          ("fltComputeIOHubThermalThresholdCritical", 539),
          ("fltComputeIOHubThermalThresholdNonRecoverable", 540),
          ("fltComputePoolEmpty", 463),
          ("fltComputeRtcBatteryInoperable", 533),
          ("fltDcxNsFailed", 304),
          ("fltDcxVIfLinkState", 479),
          ("fltDcxVcDown", 283),
          ("fltDcxVcMgmtVifDown", 459),
          ("fltEquipmentChassisIdentity", 404),
          ("fltEquipmentChassisIdentityUnestablishable", 543),
          ("fltEquipmentChassisInoperable", 456),
          ("fltEquipmentChassisPowerProblem", 408),
          ("fltEquipmentChassisThermalThresholdCritical", 409),
          ("fltEquipmentChassisThermalThresholdNonCritical", 410),
          ("fltEquipmentChassisThermalThresholdNonRecoverable", 411),
          ("fltEquipmentChassisUnacknowledged", 400),
          ("fltEquipmentChassisUnsupportedConnectivity", 399),
          ("fltEquipmentFanDegraded", 371),
          ("fltEquipmentFanInoperable", 373),
          ("fltEquipmentFanMissing", 434),
          ("fltEquipmentFanModuleDegraded", 480),
          ("fltEquipmentFanModuleIdentity", 406),
          ("fltEquipmentFanModuleMissing", 377),
          ("fltEquipmentFanModuleThermalThresholdCritical", 382),
          ("fltEquipmentFanModuleThermalThresholdNonCritical", 380),
          ("fltEquipmentFanModuleThermalThresholdNonRecoverable", 384),
          ("fltEquipmentFanPerfThresholdCritical", 396),
          ("fltEquipmentFanPerfThresholdLowerNonRecoverable", 484),
          ("fltEquipmentFanPerfThresholdNonCritical", 395),
          ("fltEquipmentFanPerfThresholdNonRecoverable", 397),
          ("fltEquipmentIOCardAutoUpgradingFirmware", 435),
          ("fltEquipmentIOCardFirmwareUpgrade", 398),
          ("fltEquipmentIOCardIdentity", 405),
          ("fltEquipmentIOCardInaccessible", 478),
          ("fltEquipmentIOCardPeerDisconnected", 403),
          ("fltEquipmentIOCardPostFailure", 481),
          ("fltEquipmentIOCardRemoved", 376),
          ("fltEquipmentIOCardThermalProblem", 379),
          ("fltEquipmentIOCardUnacknowledged", 402),
          ("fltEquipmentIOCardUnsupportedConnectivity", 401),
          ("fltEquipmentPsuIdentity", 407),
          ("fltEquipmentPsuInoperable", 374),
          ("fltEquipmentPsuMissing", 378),
          ("fltEquipmentPsuOffline", 528),
          ("fltEquipmentPsuPerfThresholdCritical", 393),
          ("fltEquipmentPsuPerfThresholdNonCritical", 392),
          ("fltEquipmentPsuPerfThresholdNonRecoverable", 394),
          ("fltEquipmentPsuPowerSupplyProblem", 369),
          ("fltEquipmentPsuThermalThresholdCritical", 383),
          ("fltEquipmentPsuThermalThresholdNonCritical", 381),
          ("fltEquipmentPsuThermalThresholdNonRecoverable", 385),
          ("fltEquipmentPsuVoltageThresholdCritical", 389),
          ("fltEquipmentPsuVoltageThresholdNonCritical", 387),
          ("fltEquipmentPsuVoltageThresholdNonRecoverable", 391),
          ("fltEtherServerIntFIoHardwareFailure", 458),
          ("fltEtherSwitchIntFIoSatelliteConnectionAbsent", 367),
          ("fltEtherSwitchIntFIoSatelliteWiringNumbersUnexpected", 440),
          ("fltEtherSwitchIntFIoSatelliteWiringProblem", 368),
          ("fltFabricComputeSlotEpMisplacedInChassisSlot", 156),
          ("fltFabricComputeSlotEpServerIdentificationProblem", 157),
          ("fltFabricExternalPcDown", 282),
          ("fltFcpoolInitiatorsEmpty", 476),
          ("fltFirmwareBootUnitCantBoot", 471),
          ("fltFirmwarePackItemImageMissing", 436),
          ("fltFirmwareUpdatableImageUnusable", 470),
          ("fltIppoolPoolEmpty", 465),
          ("fltLsServerAssociationFailed", 332),
          ("fltLsServerConfigFailure", 327),
          ("fltLsServerDiscoveryFailed", 326),
          ("fltLsServerFailed", 324),
          ("fltLsServerInaccessible", 331),
          ("fltLsServerMaintenanceFailed", 329),
          ("fltLsServerRemoved", 330),
          ("fltLsServerServerUnfulfilled", 337),
          ("fltLsServerUnassociated", 334),
          ("fltMacpoolPoolEmpty", 466),
          ("fltMemoryArrayVoltageThresholdCritical", 190),
          ("fltMemoryArrayVoltageThresholdNonCritical", 189),
          ("fltMemoryArrayVoltageThresholdNonRecoverable", 191),
          ("fltMemoryBufferUnitThermalThresholdCritical", 536),
          ("fltMemoryBufferUnitThermalThresholdNonCritical", 535),
          ("fltMemoryBufferUnitThermalThresholdNonRecoverable", 537),
          ("fltMemoryUnitDegraded", 184),
          ("fltMemoryUnitIdentityUnestablishable", 502),
          ("fltMemoryUnitInoperable", 185),
          ("fltMemoryUnitThermalThresholdCritical", 187),
          ("fltMemoryUnitThermalThresholdNonCritical", 186),
          ("fltMemoryUnitThermalThresholdNonRecoverable", 188),
          ("fltMgmtEntityChassis1SEEPROMError", 453),
          ("fltMgmtEntityChassis2SEEPROMError", 454),
          ("fltMgmtEntityChassis3SEEPROMError", 455),
          ("fltMgmtEntityDegraded", 293),
          ("fltMgmtEntityDown", 294),
          ("fltMgmtEntityElectionFailure", 428),
          ("fltMgmtEntityHaNotReady", 429),
          ("fltMgmtEntityManagementServicesFailure", 451),
          ("fltMgmtEntityManagementServicesUnresponsive", 452),
          ("fltMgmtEntityVersionIncompatible", 430),
          ("fltNetworkElementInoperable", 291),
          ("fltPortPIoFailed", 277),
          ("fltPortPIoHardwareFailure", 278),
          ("fltPortPIoLinkDown", 276),
          ("fltPortPIoSfpNotPresent", 279),
          ("fltProcessorUnitInoperable", 174),
          ("fltProcessorUnitThermalNonCritical", 175),
          ("fltProcessorUnitThermalThresholdCritical", 176),
          ("fltProcessorUnitThermalThresholdNonRecoverable", 177),
          ("fltProcessorUnitVoltageThresholdCritical", 179),
          ("fltProcessorUnitVoltageThresholdNonCritical", 178),
          ("fltProcessorUnitVoltageThresholdNonRecoverable", 180),
          ("fltStorageItemCapacityExceeded", 182),
          ("fltStorageItemCapacityWarning", 183),
          ("fltStorageRaidBatteryInoperable", 531),
          ("fltSwVlanPortNsResourceStatus", 549),
          ("fltSysdebugMEpLogMEpLogFull", 462),
          ("fltSysdebugMEpLogMEpLogLog", 460),
          ("fltSysdebugMEpLogMEpLogVeryLow", 461),
          ("fltSysdebugMEpLogTransferError", 532),
          ("fltUuidpoolPoolEmpty", 464),
          ("fltVnicEtherConfigFailed", 169),
          ("fltVnicFcConfigFailed", 170),
          ("fsmFailAaaRealmUpdateRealm", 999620),
          ("fsmFailAaaUserEpUpdateUserEp", 999621),
          ("fsmFailAdaptorExtEthIfPathReset", 999892),
          ("fsmFailAdaptorHostFcIfCircuitReset", 999897),
          ("fsmFailAdaptorHostFcIfResetFcPersBinding", 999574),
          ("fsmFailCallhomeEpConfigCallhome", 999710),
          ("fsmFailCapabilityCatalogueDeployCatalogue", 999971),
          ("fsmFailCapabilityUpdaterUpdater", 999944),
          ("fsmFailCommSvcEpRestartWebSvc", 999617),
          ("fsmFailCommSvcEpUpdateSvcEp", 999616),
          ("fsmFailComputeBladeActivateAdaptor", 999699),
          ("fsmFailComputeBladeAssociate", 999561),
          ("fsmFailComputeBladeBiosProfile", 999931),
          ("fsmFailComputeBladeBiosRecovery", 999571),
          ("fsmFailComputeBladeCmosReset", 999572),
          ("fsmFailComputeBladeConfigSoL", 999779),
          ("fsmFailComputeBladeDecommission", 999563),
          ("fsmFailComputeBladeDiag", 999575),
          ("fsmFailComputeBladeDisassociate", 999562),
          ("fsmFailComputeBladeDiscover", 999560),
          ("fsmFailComputeBladeHardShutdown", 999565),
          ("fsmFailComputeBladeHardreset", 999568),
          ("fsmFailComputeBladePowerCap", 999930),
          ("fsmFailComputeBladePowercycle", 999874),
          ("fsmFailComputeBladeResetBmc", 999842),
          ("fsmFailComputeBladeSoftShutdown", 999564),
          ("fsmFailComputeBladeSoftreset", 999569),
          ("fsmFailComputeBladeSwConnUpd", 999570),
          ("fsmFailComputeBladeTurnup", 999566),
          ("fsmFailComputeBladeUnconfigSoL", 999780),
          ("fsmFailComputeBladeUpdateAdaptor", 999698),
          ("fsmFailComputeBladeUpdateBoardController", 999970),
          ("fsmFailComputeBladeUpdateExtUsers", 999618),
          ("fsmFailEpqosDefinitionDelTaskRemove", 999790),
          ("fsmFailEquipmentChassisPsuPolicyConfig", 999573),
          ("fsmFailEquipmentChassisRemoveChassis", 999447),
          ("fsmFailEquipmentIOCardFeConn", 999446),
          ("fsmFailEquipmentIOCardFePresence", 999445),
          ("fsmFailEquipmentIOCardResetCmc", 999843),
          ("fsmFailEquipmentLocatorLedSetLocatorLed", 999448),
          ("fsmFailExtvmmKeyStoreCertInstall", 999920),
          ("fsmFailExtvmmProviderConfig", 999919),
          ("fsmFailExtvmmSwitchDelTaskRemoveProvider", 999921),
          ("fsmFailFabricComputeSlotEpIdentify", 999559),
          ("fsmFailFabricLanCloudSwitchMode", 999579),
          ("fsmFailFirmwareDownloaderDownload", 999690),
          ("fsmFailFirmwareImageDelete", 999691),
          ("fsmFailMgmtBackupBackup", 999723),
          ("fsmFailMgmtControllerActivateBMC", 999697),
          ("fsmFailMgmtControllerActivateIOM", 999695),
          ("fsmFailMgmtControllerExtMgmtIfConfig", 999558),
          ("fsmFailMgmtControllerSysConfig", 999863),
          ("fsmFailMgmtControllerUpdateBMC", 999696),
          ("fsmFailMgmtControllerUpdateIOM", 999694),
          ("fsmFailMgmtControllerUpdateSwitch", 999693),
          ("fsmFailMgmtControllerUpdateUCSManager", 999855),
          ("fsmFailMgmtIfDisableVip", 999721),
          ("fsmFailMgmtIfEnableHA", 999722),
          ("fsmFailMgmtIfEnableVip", 999720),
          ("fsmFailMgmtIfSwMgmtInbandIfConfig", 999714),
          ("fsmFailMgmtIfSwMgmtOobIfConfig", 999713),
          ("fsmFailMgmtIfVirtualIfConfig", 999719),
          ("fsmFailMgmtImporterImport", 999724),
          ("fsmFailQosclassDefinitionConfigGlobalQoS", 999785),
          ("fsmFailStatsCollectionPolicyUpdateEp", 999619),
          ("fsmFailSyntheticFsObjCreate", 999681),
          ("fsmFailSysdebugAutoCoreFileExportTargetConfigure", 999645),
          ("fsmFailSysdebugLogControlEpLogControlPersist", 999646),
          ("fsmFailSysdebugManualCoreFileExportTargetExport", 999644),
          ("fsmFailSysfileMutationGlobal", 999641),
          ("fsmFailSysfileMutationSingle", 999640),
          ("fsmFailVnicProfileSetDeploy", 999590),
          ("fsmRmtErrAaaRealmUpdateRealmSetRealmPeer", 78020),
          ("fsmRmtErrAaaUserEpUpdateUserEpSetUserPeer", 78021),
          ("fsmRmtErrAdaptorExtEthIfPathResetEnable", 78292),
          ("fsmRmtErrAdaptorHostFcIfCircuitResetEnableB", 78297),
          ("fsmRmtErrAdaptorHostFcIfResetFcPersBindingExecute", 77974),
          ("fsmRmtErrCallhomeEpConfigCallhomeSetPeer", 78110),
          ("fsmRmtErrCapabilityCatalogueDeployCatalogueFinalize", 78371),
          ("fsmRmtErrCapabilityUpdaterUpdaterUnpackLocal", 78344),
          ("fsmRmtErrCommSvcEpRestartWebSvcRestart", 78017),
          ("fsmRmtErrCommSvcEpUpdateSvcEpSetEpPeer", 78016),
          ("fsmRmtErrComputeBladeActivateAdaptorReset", 78099),
          ("fsmRmtErrComputeBladeAssociateWaitForIBMCFwUpdate", 77961),
          ("fsmRmtErrComputeBladeBiosProfileConfigure", 78331),
          ("fsmRmtErrComputeBladeBiosRecoveryWait", 77971),
          ("fsmRmtErrComputeBladeCmosResetSanitize", 77972),
          ("fsmRmtErrComputeBladeConfigSoLExecute", 78179),
          ("fsmRmtErrComputeBladeDecommissionExecute", 77963),
          ("fsmRmtErrComputeBladeDiagUnconfigUserAccess", 77975),
          ("fsmRmtErrComputeBladeDisassociateHagPnuOSDisconnect", 77962),
          ("fsmRmtErrComputeBladeDiscoverHagDisconnect", 77960),
          ("fsmRmtErrComputeBladeHardShutdownExecute", 77965),
          ("fsmRmtErrComputeBladeHardresetSanitize", 77968),
          ("fsmRmtErrComputeBladePowerCapConfig", 78330),
          ("fsmRmtErrComputeBladePowercycleSanitize", 78274),
          ("fsmRmtErrComputeBladeResetBmcExecute", 78242),
          ("fsmRmtErrComputeBladeSoftShutdownExecute", 77964),
          ("fsmRmtErrComputeBladeSoftresetSanitize", 77969),
          ("fsmRmtErrComputeBladeSwConnUpdB", 77970),
          ("fsmRmtErrComputeBladeTurnupExecute", 77966),
          ("fsmRmtErrComputeBladeUnconfigSoLExecute", 78180),
          ("fsmRmtErrComputeBladeUpdateAdaptorUpdateRequest", 78098),
          ("fsmRmtErrComputeBladeUpdateBoardControllerUpdateRequest", 78370),
          ("fsmRmtErrComputeBladeUpdateExtUsersDeploy", 78018),
          ("fsmRmtErrEpqosDefinitionDelTaskRemovePeer", 78190),
          ("fsmRmtErrEquipmentChassisPsuPolicyConfigExecute", 77973),
          ("fsmRmtErrEquipmentChassisRemoveChassisDecomission", 77847),
          ("fsmRmtErrEquipmentIOCardFeConnEnableChassis", 77846),
          ("fsmRmtErrEquipmentIOCardFePresenceIdentify", 77845),
          ("fsmRmtErrEquipmentIOCardResetCmcExecute", 78243),
          ("fsmRmtErrEquipmentLocatorLedSetLocatorLedExecute", 77848),
          ("fsmRmtErrExtvmmKeyStoreCertInstallSetPeer", 78320),
          ("fsmRmtErrExtvmmProviderConfigSetPeer", 78319),
          ("fsmRmtErrExtvmmSwitchDelTaskRemoveProviderRemoveLocal", 78321),
          ("fsmRmtErrFabricComputeSlotEpIdentifyExecutePeer", 77959),
          ("fsmRmtErrFabricLanCloudSwitchModeSwConfigPeer", 77979),
          ("fsmRmtErrFirmwareDownloaderDownloadUnpackLocal", 78090),
          ("fsmRmtErrFirmwareImageDeleteRemote", 78091),
          ("fsmRmtErrMgmtBackupBackupUpload", 78123),
          ("fsmRmtErrMgmtControllerActivateBMCReset", 78097),
          ("fsmRmtErrMgmtControllerActivateIOMReset", 78095),
          ("fsmRmtErrMgmtControllerExtMgmtIfConfigSecondary", 77958),
          ("fsmRmtErrMgmtControllerSysConfigSecondary", 78263),
          ("fsmRmtErrMgmtControllerUpdateBMCUpdateRequest", 78096),
          ("fsmRmtErrMgmtControllerUpdateIOMUpdateRequest", 78094),
          ("fsmRmtErrMgmtControllerUpdateSwitchVerifyRemote", 78093),
          ("fsmRmtErrMgmtControllerUpdateUCSManagerStart", 78255),
          ("fsmRmtErrMgmtIfDisableVipPeer", 78121),
          ("fsmRmtErrMgmtIfEnableHALocal", 78122),
          ("fsmRmtErrMgmtIfEnableVipLocal", 78120),
          ("fsmRmtErrMgmtIfSwMgmtInbandIfConfigSwitch", 78114),
          ("fsmRmtErrMgmtIfSwMgmtOobIfConfigSwitch", 78113),
          ("fsmRmtErrMgmtIfVirtualIfConfigRemote", 78119),
          ("fsmRmtErrMgmtImporterImportReportResults", 78124),
          ("fsmRmtErrQosclassDefinitionConfigGlobalQoSSetPeer", 78185),
          ("fsmRmtErrStatsCollectionPolicyUpdateEpSetEpB", 78019),
          ("fsmRmtErrSyntheticFsObjCreateCreateRemote", 78081),
          ("fsmRmtErrSysdebugAutoCoreFileExportTargetConfigurePeer", 78045),
          ("fsmRmtErrSysdebugLogControlEpLogControlPersistPeer", 78046),
          ("fsmRmtErrSysdebugManualCoreFileExportTargetExportExecute", 78044),
          ("fsmRmtErrSysfileMutationGlobalPeer", 78041),
          ("fsmRmtErrSysfileMutationSingleExecute", 78040),
          ("fsmRmtErrVnicProfileSetDeployPeer", 77990),
          ("fsmStFailAaaRealmUpdateRealmSetRealmPeer", 16580),
          ("fsmStFailAaaUserEpUpdateUserEpSetUserPeer", 16581),
          ("fsmStFailAdaptorExtEthIfPathResetEnable", 16852),
          ("fsmStFailAdaptorHostFcIfCircuitResetEnableB", 16857),
          ("fsmStFailAdaptorHostFcIfResetFcPersBindingExecute", 16534),
          ("fsmStFailCallhomeEpConfigCallhomeSetPeer", 16670),
          ("fsmStFailCapabilityCatalogueDeployCatalogueFinalize", 16931),
          ("fsmStFailCapabilityUpdaterUpdaterUnpackLocal", 16904),
          ("fsmStFailCommSvcEpRestartWebSvcRestart", 16577),
          ("fsmStFailCommSvcEpUpdateSvcEpSetEpPeer", 16576),
          ("fsmStFailComputeBladeActivateAdaptorReset", 16659),
          ("fsmStFailComputeBladeAssociateWaitForIBMCFwUpdate", 16521),
          ("fsmStFailComputeBladeBiosProfileConfigure", 16891),
          ("fsmStFailComputeBladeBiosRecoveryWait", 16531),
          ("fsmStFailComputeBladeCmosResetSanitize", 16532),
          ("fsmStFailComputeBladeConfigSoLExecute", 16739),
          ("fsmStFailComputeBladeDecommissionExecute", 16523),
          ("fsmStFailComputeBladeDiagUnconfigUserAccess", 16535),
          ("fsmStFailComputeBladeDisassociateHagPnuOSDisconnect", 16522),
          ("fsmStFailComputeBladeDiscoverHagDisconnect", 16520),
          ("fsmStFailComputeBladeHardShutdownExecute", 16525),
          ("fsmStFailComputeBladeHardresetSanitize", 16528),
          ("fsmStFailComputeBladePowerCapConfig", 16890),
          ("fsmStFailComputeBladePowercycleSanitize", 16834),
          ("fsmStFailComputeBladeResetBmcExecute", 16802),
          ("fsmStFailComputeBladeSoftShutdownExecute", 16524),
          ("fsmStFailComputeBladeSoftresetSanitize", 16529),
          ("fsmStFailComputeBladeSwConnUpdB", 16530),
          ("fsmStFailComputeBladeTurnupExecute", 16526),
          ("fsmStFailComputeBladeUnconfigSoLExecute", 16740),
          ("fsmStFailComputeBladeUpdateAdaptorUpdateRequest", 16658),
          ("fsmStFailComputeBladeUpdateBoardControllerUpdateRequest", 16930),
          ("fsmStFailComputeBladeUpdateExtUsersDeploy", 16578),
          ("fsmStFailEpqosDefinitionDelTaskRemovePeer", 16750),
          ("fsmStFailEquipmentChassisPsuPolicyConfigExecute", 16533),
          ("fsmStFailEquipmentChassisRemoveChassisDecomission", 16407),
          ("fsmStFailEquipmentIOCardFeConnEnableChassis", 16406),
          ("fsmStFailEquipmentIOCardFePresenceIdentify", 16405),
          ("fsmStFailEquipmentIOCardResetCmcExecute", 16803),
          ("fsmStFailEquipmentLocatorLedSetLocatorLedExecute", 16408),
          ("fsmStFailExtvmmKeyStoreCertInstallSetPeer", 16880),
          ("fsmStFailExtvmmProviderConfigSetPeer", 16879),
          ("fsmStFailExtvmmSwitchDelTaskRemoveProviderRemoveLocal", 16881),
          ("fsmStFailFabricComputeSlotEpIdentifyExecutePeer", 16519),
          ("fsmStFailFabricLanCloudSwitchModeSwConfigPeer", 16539),
          ("fsmStFailFirmwareDownloaderDownloadUnpackLocal", 16650),
          ("fsmStFailFirmwareImageDeleteRemote", 16651),
          ("fsmStFailMgmtBackupBackupUpload", 16683),
          ("fsmStFailMgmtControllerActivateBMCReset", 16657),
          ("fsmStFailMgmtControllerActivateIOMReset", 16655),
          ("fsmStFailMgmtControllerExtMgmtIfConfigSecondary", 16518),
          ("fsmStFailMgmtControllerSysConfigSecondary", 16823),
          ("fsmStFailMgmtControllerUpdateBMCUpdateRequest", 16656),
          ("fsmStFailMgmtControllerUpdateIOMUpdateRequest", 16654),
          ("fsmStFailMgmtControllerUpdateSwitchVerifyRemote", 16653),
          ("fsmStFailMgmtControllerUpdateUCSManagerStart", 16815),
          ("fsmStFailMgmtIfDisableVipPeer", 16681),
          ("fsmStFailMgmtIfEnableHALocal", 16682),
          ("fsmStFailMgmtIfEnableVipLocal", 16680),
          ("fsmStFailMgmtIfSwMgmtInbandIfConfigSwitch", 16674),
          ("fsmStFailMgmtIfSwMgmtOobIfConfigSwitch", 16673),
          ("fsmStFailMgmtIfVirtualIfConfigRemote", 16679),
          ("fsmStFailMgmtImporterImportReportResults", 16684),
          ("fsmStFailQosclassDefinitionConfigGlobalQoSSetPeer", 16745),
          ("fsmStFailStatsCollectionPolicyUpdateEpSetEpB", 16579),
          ("fsmStFailSyntheticFsObjCreateCreateRemote", 16641),
          ("fsmStFailSysdebugAutoCoreFileExportTargetConfigurePeer", 16605),
          ("fsmStFailSysdebugLogControlEpLogControlPersistPeer", 16606),
          ("fsmStFailSysdebugManualCoreFileExportTargetExportExecute", 16604),
          ("fsmStFailSysfileMutationGlobalPeer", 16601),
          ("fsmStFailSysfileMutationSingleExecute", 16600),
          ("fsmStFailVnicProfileSetDeployPeer", 16550))
    )



class CucsFaultType(Integer32, TextualConvention):
    status = "current"
    subtypeSpec = Integer32.subtypeSpec
    subtypeSpec += ConstraintsUnion(
        SingleValueConstraint(
            *(1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9)
        )
    )
    namedValues = NamedValues(
        *(("configuration", 4),
          ("connectivity", 7),
          ("environmental", 5),
          ("equipment", 2),
          ("fsm", 1),
          ("management", 6),
          ("network", 8),
          ("operational", 9),
          ("server", 3))
    )



class CucsFaultProbableCause(Integer32, TextualConvention):
    status = "current"
    subtypeSpec = Integer32.subtypeSpec
    subtypeSpec += ConstraintsUnion(
        SingleValueConstraint(
            *(3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35,
              36,
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47,
              48,
              49,
              50,
              51,
              52,
              53,
              54,
              55,
              56,
              57,
              58,
              59,
              60,
              61,
              62,
              63,
              64,
              65,
              66,
              67,
              68,
              69,
              70,
              71,
              74,
              75,
              76,
              77,
              78,
              79,
              80,
              81,
              82,
              83,
              84,
              85,
              86,
              87,
              88,
              89,
              90,
              91,
              92,
              93,
              94,
              95,
              96,
              97,
              98,
              99,
              100,
              101,
              102,
              103,
              104,
              105,
              106,
              107,
              108,
              109,
              110,
              111,
              112,
              113,
              114,
              115,
              116,
              117,
              118,
              119,
              120,
              121,
              122,
              123,
              124,
              125,
              126,
              127,
              128,
              129,
              130,
              131,
              132,
              133,
              134,
              135,
              136,
              137,
              138,
              139,
              140,
              141,
              142,
              143,
              144,
              145,
              146,
              147,
              148,
              149,
              150,
              151,
              152,
              153,
              154,
              155,
              156,
              157,
              158,
              159,
              160,
              161,
              162,
              163,
              164,
              165,
              166,
              167,
              168,
              169,
              170,
              171,
              172,
              173,
              174,
              175,
              176,
              177,
              178,
              179,
              180,
              181,
              182,
              183,
              184,
              185,
              186,
              187,
              188,
              189,
              190,
              191,
              192,
              193,
              194,
              195,
              196,
              197,
              198,
              199,
              200,
              201,
              202,
              203,
              204,
              205,
              206,
              207,
              208,
              209,
              210,
              211,
              212,
              213,
              214,
              215,
              216,
              217,
              218,
              219,
              220,
              221,
              222,
              223,
              224,
              225,
              228,
              229,
              230,
              231,
              232,
              233,
              234,
              235,
              236,
              237,
              238,
              239,
              241,
              242,
              243,
              244,
              245,
              246,
              247,
              263,
              264,
              265,
              266,
              267,
              268,
              269,
              270,
              271,
              272,
              273,
              275,
              276,
              277,
              278,
              279,
              280,
              281,
              282,
              283,
              284)
        )
    )
    namedValues = NamedValues(
        *(("aFailed", 142),
          ("activateAdaptorNwFwFailed", 109),
          ("activateFailed", 201),
          ("activateibmcfwFailed", 102),
          ("applyFailed", 206),
          ("associationFailed", 245),
          ("autoFirmwareUpgrade", 282),
          ("bFailed", 143),
          ("backupLocalFailed", 228),
          ("biosImgUpdateFailed", 112),
          ("biosPostCompletionFailed", 36),
          ("bladeBootFailed", 34),
          ("bladeBootHostFailed", 126),
          ("bladeBootPnuosFailed", 85),
          ("bladeBootWaitFailed", 35),
          ("bladePowerOffFailed", 104),
          ("bladePowerOnFailed", 21),
          ("bladeReadBiosSettingsFailed", 38),
          ("bladeReadSmbiosFailed", 37),
          ("bladeShutdownFailed", 138),
          ("bmcInventoryFailed", 18),
          ("bmcPresenceFailed", 17),
          ("bmcShutdownDiagCompletedFailed", 70),
          ("bmcShutdownDiscoveredFailed", 98),
          ("capacityExceeded", 159),
          ("chassisSeepromError", 237),
          ("checkLicenseFailed", 4),
          ("cleanupFailed", 146),
          ("cmcVifDown", 220),
          ("configBiosFailed", 135),
          ("configFailed", 141),
          ("configFeLocalFailed", 19),
          ("configFePeerFailed", 20),
          ("configSoLfailed", 123),
          ("configSolFailed", 26),
          ("configUserAccessFailed", 25),
          ("configUuidFailed", 125),
          ("configurationFailed", 155),
          ("configurationFailure", 264),
          ("configureEndPointFailed", 8),
          ("configureFailed", 148),
          ("configureSwMgmtEndPointFailed", 6),
          ("configureVifNsFailed", 7),
          ("connectivityProblem", 178),
          ("copyRemoteFailed", 191),
          ("createLocalFailed", 187),
          ("createRemoteFailed", 188),
          ("debugWaitFailed", 58),
          ("decomissionFailed", 11),
          ("deleteLocalFailed", 190),
          ("deployFailed", 168),
          ("deriveConfigFailed", 24),
          ("disableAfailed", 182),
          ("disableBfailed", 184),
          ("disableEndPointFailed", 12),
          ("disableFailed", 180),
          ("disableServerConnSwAfailed", 52),
          ("disableServerConnSwBfailed", 48),
          ("discoverChassisFailed", 9),
          ("discoveryFailed", 244),
          ("downloadLocalFailed", 230),
          ("electionFailure", 232),
          ("emptyPool", 225),
          ("enableAfailed", 183),
          ("enableBfailed", 185),
          ("enableChassisFailed", 10),
          ("enableFailed", 181),
          ("enableServerConnSwAfailed", 55),
          ("enableServerConnSwBfailed", 51),
          ("equipmentDegraded", 160),
          ("equipmentDisconnected", 283),
          ("equipmentInaccessible", 246),
          ("equipmentInoperable", 156),
          ("equipmentMissing", 177),
          ("equipmentOffline", 277),
          ("equipmentProblem", 247),
          ("equipmentRemoved", 266),
          ("equipmentUnacknowledged", 281),
          ("evaluateStatusFailed", 71),
          ("executeFailed", 16),
          ("executeLocalFailed", 76),
          ("executePeerFailed", 77),
          ("fabricatrafficTestStatusFailed", 50),
          ("fabricbtrafficTestStatusFailed", 54),
          ("fileTransferFailed", 239),
          ("finalizeFailed", 216),
          ("firmwareUpgradeProblem", 279),
          ("fruProblem", 284),
          ("fsmFailed", 3),
          ("generateLogWaitFailed", 57),
          ("generateReportFailed", 56),
          ("getVersionFailed", 269),
          ("haNotReady", 235),
          ("hagConnectFailed", 86),
          ("hagDisconnectFailed", 97),
          ("hagHostosconnectFailed", 127),
          ("hagPnuosconnectFailed", 110),
          ("hagPnuosdisconnectFailed", 122),
          ("handlePoolingFailed", 99),
          ("hbaImgUpdateFailed", 114),
          ("hostConnectFailed", 39),
          ("hostDisconnectFailed", 69),
          ("hostIdentFailed", 42),
          ("hostInventoryFailed", 45),
          ("hostPolicyFailed", 43),
          ("hostServerDiagFailed", 46),
          ("hostServerDiagStatusFailed", 47),
          ("hostosconfigFailed", 131),
          ("hostosidentFailed", 128),
          ("hostospolicyFailed", 129),
          ("hostosvalidateFailed", 130),
          ("identifyFailed", 5),
          ("identityUnestablishable", 161),
          ("imageCannotBoot", 205),
          ("imageDeleted", 203),
          ("imageUnusable", 204),
          ("insufficientResources", 241),
          ("insufficientlyEquipped", 242),
          ("interfaceFailed", 218),
          ("limitReached", 224),
          ("linkDown", 179),
          ("localFailed", 153),
          ("logCapacity", 238),
          ("maintenanceFailed", 265),
          ("managementServicesFailure", 233),
          ("managementServicesUnresponsive", 234),
          ("nicConfigFailed", 29),
          ("nicConfigHostosFailed", 121),
          ("nicConfigPnuosFailed", 80),
          ("nicImgUpdateFailed", 115),
          ("nicInventoryFailed", 23),
          ("nicPresenceFailed", 22),
          ("nicUnconfigFailed", 61),
          ("nicUnconfigHostosFailed", 132),
          ("nicUnconfigPnuosFailed", 92),
          ("operationalStateDown", 219),
          ("peerFailed", 154),
          ("performanceProblem", 278),
          ("pnuosconfigFailed", 116),
          ("pnuosidentFailed", 87),
          ("pnuosinventoryFailed", 89),
          ("pnuoslocalDiskConfigFailed", 117),
          ("pnuospolicyFailed", 88),
          ("pnuosscrubFailed", 91),
          ("pnuosselfTestFailed", 90),
          ("pnuosunconfigFailed", 136),
          ("pnuosunloadDriversFailed", 118),
          ("pnuosvalidateFailed", 111),
          ("pollBoardCtrlUpdateStatusFailed", 106),
          ("pollMemoryTestStatusFailed", 41),
          ("pollUpdateStatusFailed", 200),
          ("portFailed", 217),
          ("powerProblem", 243),
          ("preSanitizeFailed", 78),
          ("prepareForBootFailed", 124),
          ("prepareForUpdateFailed", 202),
          ("primaryFailed", 74),
          ("propogateEpSettingsFailed", 164),
          ("propogateEpTimeZoneSettingsLocalFailed", 165),
          ("propogateEpTimeZoneSettingsPeerFailed", 166),
          ("reconfigBiosFailed", 149),
          ("reconfigUuidFailed", 150),
          ("remoteFailed", 192),
          ("removeConfigFailed", 64),
          ("removeLocalFailed", 270),
          ("removevmediaLocalFailed", 59),
          ("removevmediaPeerFailed", 60),
          ("reportResultsFailed", 231),
          ("rescanImagesFailed", 207),
          ("resetFailed", 147),
          ("resetLocalFailed", 195),
          ("resetRemoteFailed", 198),
          ("resetibmcFailed", 103),
          ("restartFailed", 167),
          ("restoreConfigFeLocalFailed", 65),
          ("restoreConfigFePeerFailed", 66),
          ("sanitizeFailed", 79),
          ("satelliteConnectionAbsent", 273),
          ("satelliteMisConnected", 275),
          ("secondaryFailed", 75),
          ("serverFailed", 263),
          ("serverIdentificationProblem", 152),
          ("serverInaccessible", 267),
          ("serverMoved", 151),
          ("setDiagUserFailed", 44),
          ("setEpAfailed", 271),
          ("setEpBfailed", 272),
          ("setEpLocalFailed", 162),
          ("setEpPeerFailed", 163),
          ("setKeyRingLocalFailed", 173),
          ("setKeyRingPeerFailed", 174),
          ("setLocalFailed", 221),
          ("setPeerFailed", 222),
          ("setRealmLocalFailed", 169),
          ("setRealmPeerFailed", 170),
          ("setUserLocalFailed", 171),
          ("setUserPeerFailed", 172),
          ("setupVmediaLocalFailed", 83),
          ("setupVmediaPeerFailed", 84),
          ("setupvmediaLocalFailed", 32),
          ("setupvmediaPeerFailed", 33),
          ("shutdownFailed", 144),
          ("startFabricatrafficTestFailed", 49),
          ("startFabricbtrafficTestFailed", 53),
          ("startFailed", 145),
          ("startMemoryTestStatusFailed", 40),
          ("stopvmediaLocalFailed", 30),
          ("stopvmediaPeerFailed", 31),
          ("storageCtlrImgUpdateFailed", 113),
          ("swConfigHostoslocalFailed", 119),
          ("swConfigHostospeerFailed", 120),
          ("swConfigLocalFailed", 27),
          ("swConfigPeerFailed", 28),
          ("swConfigPnuoslocalFailed", 81),
          ("swConfigPnuospeerFailed", 82),
          ("swUnconfigHostoslocalFailed", 133),
          ("swUnconfigHostospeerFailed", 134),
          ("swUnconfigLocalFailed", 62),
          ("swUnconfigPeerFailed", 63),
          ("swUnconfigPnuoslocalFailed", 93),
          ("swUnconfigPnuospeerFailed", 94),
          ("switchFailed", 223),
          ("syncBladeaglocalFailed", 208),
          ("syncBladeagremoteFailed", 209),
          ("syncHostagentaglocalFailed", 214),
          ("syncHostagentagremoteFailed", 215),
          ("syncNicaglocalFailed", 210),
          ("syncNicagremoteFailed", 211),
          ("syncPortaglocalFailed", 212),
          ("syncPortagremoteFailed", 213),
          ("teardownVmediaLocalFailed", 95),
          ("teardownVmediaPeerFailed", 96),
          ("thermalProblem", 157),
          ("unIdentifyLocalFailed", 13),
          ("unIdentifyPeerFailed", 14),
          ("unassociated", 268),
          ("unconfigBiosFailed", 139),
          ("unconfigSoLfailed", 140),
          ("unconfigSolFailed", 68),
          ("unconfigUserAccessFailed", 67),
          ("unconfigUuidFailed", 137),
          ("unexpectedNumberOfLinks", 276),
          ("unidentifiableFru", 176),
          ("unpackLocalFailed", 189),
          ("unsupportedConnectivityConfiguration", 280),
          ("updateAdaptorNwFwFailed", 107),
          ("updateBoardCtrlRequestFailed", 105),
          ("updateConnectivityFailed", 186),
          ("updateLocalFailed", 193),
          ("updateRemoteFailed", 196),
          ("updateRequestFailed", 199),
          ("updateibmcfwFailed", 100),
          ("uploadFailed", 229),
          ("verifyLocalFailed", 194),
          ("verifyRemoteFailed", 197),
          ("versionIncompatible", 236),
          ("vifDown", 175),
          ("voltageProblem", 158),
          ("waitFailed", 15),
          ("waitForAdaptorNwFwUpdateFailed", 108),
          ("waitForibmcfwUpdateFailed", 101))
    )



class CucsFaultSeverity(Integer32, TextualConvention):
    status = "current"
    subtypeSpec = Integer32.subtypeSpec
    subtypeSpec += ConstraintsUnion(
        SingleValueConstraint(
            *(0,
              1,
              3,
              4,
              5,
              6)
        )
    )
    namedValues = NamedValues(
        *(("cleared", 0),
          ("critical", 6),
          ("info", 1),
          ("major", 5),
          ("minor", 4),
          ("warning", 3))
    )



# MIB Managed Objects in the order of their OIDs

_CiscoUnifiedComputingMIBNotifs_ObjectIdentity = ObjectIdentity
ciscoUnifiedComputingMIBNotifs = _CiscoUnifiedComputingMIBNotifs_ObjectIdentity(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 0)
)
_CiscoUnifiedComputingMIBObjects_ObjectIdentity = ObjectIdentity
ciscoUnifiedComputingMIBObjects = _CiscoUnifiedComputingMIBObjects_ObjectIdentity(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1)
)
_CucsFaultObjects_ObjectIdentity = ObjectIdentity
cucsFaultObjects = _CucsFaultObjects_ObjectIdentity(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1, 1)
)
_CucsFaultTable_Object = MibTable
cucsFaultTable = _CucsFaultTable_Object(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1, 1, 1)
)
if mibBuilder.loadTexts:
    cucsFaultTable.setStatus("current")
_CucsFaultEntry_Object = MibTableRow
cucsFaultEntry = _CucsFaultEntry_Object(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1, 1, 1, 1)
)
cucsFaultEntry.setIndexNames(
    (0, "CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultIndex"),
)
if mibBuilder.loadTexts:
    cucsFaultEntry.setStatus("current")
_CucsFaultIndex_Type = CucsManagedObjectId
_CucsFaultIndex_Object = MibTableColumn
cucsFaultIndex = _CucsFaultIndex_Object(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1, 1, 1, 1, 1),
    _CucsFaultIndex_Type()
)
cucsFaultIndex.setMaxAccess("not-accessible")
if mibBuilder.loadTexts:
    cucsFaultIndex.setStatus("current")
_CucsFaultAffectedObjectId_Type = RowPointer
_CucsFaultAffectedObjectId_Object = MibTableColumn
cucsFaultAffectedObjectId = _CucsFaultAffectedObjectId_Object(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1, 1, 1, 1, 4),
    _CucsFaultAffectedObjectId_Type()
)
cucsFaultAffectedObjectId.setMaxAccess("read-only")
if mibBuilder.loadTexts:
    cucsFaultAffectedObjectId.setStatus("current")
_CucsFaultAffectedObjectDn_Type = CucsManagedObjectDn
_CucsFaultAffectedObjectDn_Object = MibTableColumn
cucsFaultAffectedObjectDn = _CucsFaultAffectedObjectDn_Object(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1, 1, 1, 1, 5),
    _CucsFaultAffectedObjectDn_Type()
)
cucsFaultAffectedObjectDn.setMaxAccess("read-only")
if mibBuilder.loadTexts:
    cucsFaultAffectedObjectDn.setStatus("current")
_CucsFaultProbableCause_Type = CucsFaultProbableCause
_CucsFaultProbableCause_Object = MibTableColumn
cucsFaultProbableCause = _CucsFaultProbableCause_Object(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1, 1, 1, 1, 7),
    _CucsFaultProbableCause_Type()
)
cucsFaultProbableCause.setMaxAccess("read-only")
if mibBuilder.loadTexts:
    cucsFaultProbableCause.setStatus("current")
_CucsFaultCode_Type = CucsFaultCode
_CucsFaultCode_Object = MibTableColumn
cucsFaultCode = _CucsFaultCode_Object(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1, 1, 1, 1, 9),
    _CucsFaultCode_Type()
)
cucsFaultCode.setMaxAccess("read-only")
if mibBuilder.loadTexts:
    cucsFaultCode.setStatus("current")
_CucsFaultCreationTime_Type = DateAndTime
_CucsFaultCreationTime_Object = MibTableColumn
cucsFaultCreationTime = _CucsFaultCreationTime_Object(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1, 1, 1, 1, 10),
    _CucsFaultCreationTime_Type()
)
cucsFaultCreationTime.setMaxAccess("read-only")
if mibBuilder.loadTexts:
    cucsFaultCreationTime.setStatus("current")


class _CucsFaultDescription_Type(SnmpAdminString):
    """Custom type cucsFaultDescription based on SnmpAdminString"""
    subtypeSpec = SnmpAdminString.subtypeSpec
    subtypeSpec += ConstraintsUnion(
        ValueSizeConstraint(0, 255),
    )


_CucsFaultDescription_Type.__name__ = "SnmpAdminString"
_CucsFaultDescription_Object = MibTableColumn
cucsFaultDescription = _CucsFaultDescription_Object(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1, 1, 1, 1, 11),
    _CucsFaultDescription_Type()
)
cucsFaultDescription.setMaxAccess("read-only")
if mibBuilder.loadTexts:
    cucsFaultDescription.setStatus("current")
_CucsFaultLastModificationTime_Type = DateAndTime
_CucsFaultLastModificationTime_Object = MibTableColumn
cucsFaultLastModificationTime = _CucsFaultLastModificationTime_Object(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1, 1, 1, 1, 14),
    _CucsFaultLastModificationTime_Type()
)
cucsFaultLastModificationTime.setMaxAccess("read-only")
if mibBuilder.loadTexts:
    cucsFaultLastModificationTime.setStatus("current")
_CucsFaultOccur_Type = Counter32
_CucsFaultOccur_Object = MibTableColumn
cucsFaultOccur = _CucsFaultOccur_Object(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1, 1, 1, 1, 16),
    _CucsFaultOccur_Type()
)
cucsFaultOccur.setMaxAccess("read-only")
if mibBuilder.loadTexts:
    cucsFaultOccur.setStatus("current")
_CucsFaultSeverity_Type = CucsFaultSeverity
_CucsFaultSeverity_Object = MibTableColumn
cucsFaultSeverity = _CucsFaultSeverity_Object(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1, 1, 1, 1, 20),
    _CucsFaultSeverity_Type()
)
cucsFaultSeverity.setMaxAccess("read-only")
if mibBuilder.loadTexts:
    cucsFaultSeverity.setStatus("current")
_CucsFaultType_Type = CucsFaultType
_CucsFaultType_Object = MibTableColumn
cucsFaultType = _CucsFaultType_Object(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 1, 1, 1, 1, 22),
    _CucsFaultType_Type()
)
cucsFaultType.setMaxAccess("read-only")
if mibBuilder.loadTexts:
    cucsFaultType.setStatus("current")
_CiscoUnifiedComputingMIBConform_ObjectIdentity = ObjectIdentity
ciscoUnifiedComputingMIBConform = _CiscoUnifiedComputingMIBConform_ObjectIdentity(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 2)
)
_CucsFaultMIBConform_ObjectIdentity = ObjectIdentity
cucsFaultMIBConform = _CucsFaultMIBConform_ObjectIdentity(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 2, 1)
)
_CucsFaultMIBCompliances_ObjectIdentity = ObjectIdentity
cucsFaultMIBCompliances = _CucsFaultMIBCompliances_ObjectIdentity(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 2, 1, 1)
)
_CucsFaultMIBGroups_ObjectIdentity = ObjectIdentity
cucsFaultMIBGroups = _CucsFaultMIBGroups_ObjectIdentity(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 2, 1, 2)
)

# Managed Objects groups

cucsFaultsGroup = ObjectGroup(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 2, 1, 2, 1)
)
cucsFaultsGroup.setObjects(
      *(("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultDescription"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultAffectedObjectId"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultAffectedObjectDn"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultCreationTime"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultLastModificationTime"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultCode"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultType"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultProbableCause"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultSeverity"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultOccur"))
)
if mibBuilder.loadTexts:
    cucsFaultsGroup.setStatus("current")


# Notification objects

cucsFaultActiveNotif = NotificationType(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 0, 1)
)
cucsFaultActiveNotif.setObjects(
      *(("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultDescription"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultAffectedObjectId"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultAffectedObjectDn"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultCreationTime"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultLastModificationTime"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultCode"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultType"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultProbableCause"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultSeverity"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultOccur"))
)
if mibBuilder.loadTexts:
    cucsFaultActiveNotif.setStatus(
        "current"
    )

cucsFaultClearNotif = NotificationType(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 0, 2)
)
cucsFaultClearNotif.setObjects(
      *(("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultDescription"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultAffectedObjectId"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultAffectedObjectDn"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultCreationTime"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultLastModificationTime"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultCode"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultType"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultProbableCause"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultSeverity"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultOccur"))
)
if mibBuilder.loadTexts:
    cucsFaultClearNotif.setStatus(
        "current"
    )


# Notifications groups

cucsFaultsNotifGroup = NotificationGroup(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 2, 1, 2, 2)
)
cucsFaultsNotifGroup.setObjects(
      *(("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultActiveNotif"),
        ("CISCO-UNIFIED-COMPUTING-MIB", "cucsFaultClearNotif"))
)
if mibBuilder.loadTexts:
    cucsFaultsNotifGroup.setStatus(
        "current"
    )


# Agent capabilities


# Module compliance

cucsFaultMIBCompliance = ModuleCompliance(
    (1, 3, 6, 1, 4, 1, 9, 9, 719, 2, 1, 1, 1)
)
if mibBuilder.loadTexts:
    cucsFaultMIBCompliance.setStatus(
        "current"
    )


# Export all MIB objects to the MIB builder

mibBuilder.exportSymbols(
    "CISCO-UNIFIED-COMPUTING-MIB",
    **{"CucsManagedObjectId": CucsManagedObjectId,
       "CucsManagedObjectDn": CucsManagedObjectDn,
       "CucsFaultCode": CucsFaultCode,
       "CucsFaultType": CucsFaultType,
       "CucsFaultProbableCause": CucsFaultProbableCause,
       "CucsFaultSeverity": CucsFaultSeverity,
       "ciscoUnifiedComputingMIB": ciscoUnifiedComputingMIB,
       "ciscoUnifiedComputingMIBNotifs": ciscoUnifiedComputingMIBNotifs,
       "cucsFaultActiveNotif": cucsFaultActiveNotif,
       "cucsFaultClearNotif": cucsFaultClearNotif,
       "ciscoUnifiedComputingMIBObjects": ciscoUnifiedComputingMIBObjects,
       "cucsFaultObjects": cucsFaultObjects,
       "cucsFaultTable": cucsFaultTable,
       "cucsFaultEntry": cucsFaultEntry,
       "cucsFaultIndex": cucsFaultIndex,
       "cucsFaultAffectedObjectId": cucsFaultAffectedObjectId,
       "cucsFaultAffectedObjectDn": cucsFaultAffectedObjectDn,
       "cucsFaultProbableCause": cucsFaultProbableCause,
       "cucsFaultCode": cucsFaultCode,
       "cucsFaultCreationTime": cucsFaultCreationTime,
       "cucsFaultDescription": cucsFaultDescription,
       "cucsFaultLastModificationTime": cucsFaultLastModificationTime,
       "cucsFaultOccur": cucsFaultOccur,
       "cucsFaultSeverity": cucsFaultSeverity,
       "cucsFaultType": cucsFaultType,
       "ciscoUnifiedComputingMIBConform": ciscoUnifiedComputingMIBConform,
       "cucsFaultMIBConform": cucsFaultMIBConform,
       "cucsFaultMIBCompliances": cucsFaultMIBCompliances,
       "cucsFaultMIBCompliance": cucsFaultMIBCompliance,
       "cucsFaultMIBGroups": cucsFaultMIBGroups,
       "cucsFaultsGroup": cucsFaultsGroup,
       "cucsFaultsNotifGroup": cucsFaultsNotifGroup}
)
