# SNMP MIB module (IANA-ITU-ALARM-TC-MIB) expressed in pysnmp data model.
#
# This Python module is designed to be imported and executed by the
# pysnmp library.
#
# See https://www.pysnmp.com/pysnmp for further information.
#
# Notes
# -----
# ASN.1 source file:///Users/lextm/pysnmp.com/mibs.pysnmp.com/asn1/IANA-ITU-ALARM-TC-MIB
# Produced by pysmi-1.5.4 at Mon Oct 14 21:40:33 2024
# On host MacBook-Pro.local platform Darwin version 24.0.0 by user lextm
# Using Python version 3.12.0 (main, Nov 14 2023, 23:52:11) [Clang 15.0.0 (clang-1500.0.40.1)]

if 'mibBuilder' not in globals():
    import sys

    sys.stderr.write(__doc__)
    sys.exit(1)

# Import base ASN.1 objects even if this MIB does not use it

(Integer,
 OctetString,
 ObjectIdentifier) = mibBuilder.importSymbols(
    "ASN1",
    "Integer",
    "OctetString",
    "ObjectIdentifier")

(NamedValues,) = mibBuilder.importSymbols(
    "ASN1-ENUMERATION",
    "NamedValues")
(ConstraintsIntersection,
 SingleValueConstraint,
 ValueRangeConstraint,
 ValueSizeConstraint,
 ConstraintsUnion) = mibBuilder.importSymbols(
    "ASN1-REFINEMENT",
    "ConstraintsIntersection",
    "SingleValueConstraint",
    "ValueRangeConstraint",
    "ValueSizeConstraint",
    "ConstraintsUnion")

# Import SMI symbols from the MIBs this MIB depends on

(ModuleCompliance,
 NotificationGroup) = mibBuilder.importSymbols(
    "SNMPv2-CONF",
    "ModuleCompliance",
    "NotificationGroup")

(Bits,
 Counter32,
 Counter64,
 Gauge32,
 Integer32,
 IpAddress,
 ModuleIdentity,
 MibIdentifier,
 NotificationType,
 ObjectIdentity,
 MibScalar,
 MibTable,
 MibTableRow,
 MibTableColumn,
 TimeTicks,
 Unsigned32,
 iso,
 mib_2) = mibBuilder.importSymbols(
    "SNMPv2-SMI",
    "Bits",
    "Counter32",
    "Counter64",
    "Gauge32",
    "Integer32",
    "IpAddress",
    "ModuleIdentity",
    "MibIdentifier",
    "NotificationType",
    "ObjectIdentity",
    "MibScalar",
    "MibTable",
    "MibTableRow",
    "MibTableColumn",
    "TimeTicks",
    "Unsigned32",
    "iso",
    "mib-2")

(DisplayString,
 TextualConvention) = mibBuilder.importSymbols(
    "SNMPv2-TC",
    "DisplayString",
    "TextualConvention")


# MODULE-IDENTITY

ianaItuAlarmNumbers = ModuleIdentity(
    (1, 3, 6, 1, 2, 1, 119)
)
ianaItuAlarmNumbers.setRevisions(
        ("2014-05-22 00:00",
         "2004-09-09 00:00")
)


# Types definitions


# TEXTUAL-CONVENTIONS



class IANAItuProbableCause(Integer32, TextualConvention):
    status = "current"
    subtypeSpec = Integer32.subtypeSpec
    subtypeSpec += ConstraintsUnion(
        SingleValueConstraint(
            *(1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25,
              26,
              51,
              52,
              53,
              54,
              55,
              56,
              57,
              58,
              59,
              60,
              61,
              62,
              63,
              64,
              65,
              66,
              67,
              68,
              69,
              70,
              71,
              72,
              73,
              74,
              75,
              76,
              77,
              78,
              79,
              80,
              81,
              82,
              101,
              102,
              103,
              104,
              105,
              106,
              107,
              108,
              109,
              110,
              111,
              112,
              113,
              114,
              115,
              116,
              117,
              118,
              119,
              120,
              121,
              122,
              123,
              124,
              125,
              126,
              127,
              128,
              129,
              130,
              131,
              132,
              133,
              134,
              135,
              136,
              151,
              152,
              153,
              154,
              155,
              156,
              157,
              158,
              159,
              160,
              161,
              162,
              163,
              164,
              165,
              166,
              201,
              202,
              203,
              204,
              205,
              206,
              207,
              500,
              501,
              502,
              503,
              504,
              505,
              506,
              507,
              508,
              509,
              510,
              511,
              512,
              513,
              514,
              515,
              516,
              517,
              518,
              519,
              520,
              521,
              522,
              523,
              524,
              525,
              526,
              527,
              528,
              529,
              530,
              531,
              532,
              533,
              534,
              535,
              536,
              537,
              538,
              539,
              540,
              541,
              542,
              543,
              544,
              545,
              546,
              547,
              548,
              549,
              550,
              551,
              552,
              553,
              554,
              555,
              600,
              601,
              602,
              603,
              604,
              605,
              606,
              607,
              608,
              609,
              610,
              611,
              612,
              613,
              614,
              615,
              1024)
        )
    )
    namedValues = NamedValues(
        *(("aIS", 1),
          ("adapterError", 500),
          ("airCompressorFailure", 101),
          ("airConditioningFailure", 102),
          ("airDryerFailure", 103),
          ("antennaFailure", 71),
          ("applicationSubsystemFailture", 501),
          ("applicationSubsystemFailure", 158),
          ("authenticationFailure", 600),
          ("backplaneFailure", 51),
          ("bandwidthReduced", 201),
          ("bandwidthReducedX733", 502),
          ("batteryChargingFailure", 72),
          ("batteryDischarging", 104),
          ("batteryFailure", 105),
          ("breachOfConfidentiality", 601),
          ("broadcastChannelFailure", 21),
          ("cableTamper", 602),
          ("callEstablishmentError", 503),
          ("callSetUpFailure", 2),
          ("commercialPowerFailure", 106),
          ("communicationsProtocolError", 504),
          ("communicationsSubsystemFailure", 505),
          ("configurationOrCustomisationError", 159),
          ("configurationOrCustomizationError", 506),
          ("congestion", 202),
          ("congestionX733", 507),
          ("connectionEstablishmentError", 22),
          ("coolingFanFailure", 107),
          ("coolingSystemFailure", 134),
          ("corruptData", 153),
          ("coruptData", 508),
          ("cpuCyclesLimitExceeded", 509),
          ("dataSetOrModemError", 510),
          ("dataSetProblem", 52),
          ("databaseInconsistency", 160),
          ("degradedSignal", 3),
          ("degradedSignalX733", 511),
          ("delayedInformation", 603),
          ("demodulationFailure", 20),
          ("denialOfService", 604),
          ("diskFailure", 73),
          ("dteDceInterfaceError", 512),
          ("duplicateInformation", 605),
          ("enclosureDoorOpen", 118),
          ("enclosureDoorOpenX733", 513),
          ("engineFailure", 108),
          ("equipmentIdentifierDuplication", 53),
          ("equipmentMalfunction", 514),
          ("excessiveBER", 12),
          ("excessiveErrorRate", 203),
          ("excessiveResponseTime", 204),
          ("excessiveRetransmissionRate", 205),
          ("excessiveVibration", 515),
          ("explosiveGas", 119),
          ("externalEquipmentFailure", 135),
          ("externalIFDeviceProblem", 54),
          ("externalPointFailure", 136),
          ("farEndReceiverFailure", 4),
          ("fileError", 161),
          ("fileErrorX733", 516),
          ("fire", 120),
          ("fireDetected", 517),
          ("fireDetectorFailure", 109),
          ("flood", 121),
          ("framingError", 5),
          ("framingErrorX733", 518),
          ("frequencyHoppingFailure", 74),
          ("fuseFailure", 110),
          ("generatorFailure", 111),
          ("heatingVentCoolingSystemProblem", 519),
          ("highHumidity", 122),
          ("highTemperature", 123),
          ("highWind", 124),
          ("humidityUnacceptable", 520),
          ("iODeviceError", 75),
          ("iceBuildUp", 125),
          ("informationMissing", 606),
          ("informationModificationDetected", 607),
          ("informationOutOfSequence", 608),
          ("inputDeviceError", 522),
          ("inputOutputDeviceError", 521),
          ("intrusionDetection", 126),
          ("invalidMessageReceived", 23),
          ("keyExpired", 609),
          ("lanError", 523),
          ("leakDetected", 524),
          ("lineCardProblem", 55),
          ("localNodeTransmissionError", 24),
          ("localNodeTransmissionErrorX733", 525),
          ("lossOfFrame", 6),
          ("lossOfFrameX733", 526),
          ("lossOfMultiFrame", 16),
          ("lossOfPointer", 7),
          ("lossOfRealTimel", 157),
          ("lossOfRedundancy", 77),
          ("lossOfSignal", 8),
          ("lossOfSignalX733", 527),
          ("lossOfSynchronisation", 76),
          ("lowBatteryThreshold", 112),
          ("lowCablePressure", 129),
          ("lowFuel", 127),
          ("lowHumidity", 128),
          ("lowTemperatue", 130),
          ("lowWater", 131),
          ("materialSupplyExhausted", 528),
          ("memoryMismatch", 152),
          ("modulationFailure", 19),
          ("multiplexerProblem", 56),
          ("multiplexerProblemX733", 529),
          ("nEIdentifierDuplication", 57),
          ("nonRepudiationFailure", 610),
          ("other", 1024),
          ("ouputDeviceError", 531),
          ("outOfCPUCycles", 154),
          ("outOfHoursActivity", 611),
          ("outOfMemory", 162),
          ("outOfMemoryX733", 530),
          ("outOfService", 612),
          ("pathTraceMismatch", 13),
          ("payloadTypeMismatch", 9),
          ("performanceDegraded", 532),
          ("powerProblem", 58),
          ("powerProblems", 533),
          ("powerSupplyFailure", 78),
          ("pressureUnacceptable", 534),
          ("proceduralError", 613),
          ("processorProblem", 59),
          ("processorProblems", 535),
          ("protectingResourceFailure", 82),
          ("protectionMechanismFailure", 81),
          ("protectionPathFailure", 60),
          ("pumpFailure", 113),
          ("pumpFailureX733", 536),
          ("queueSizeExceeded", 537),
          ("realTimeClockFailure", 70),
          ("receiveFailure", 17),
          ("receiveFailureX733", 538),
          ("receiverFailure", 61),
          ("receiverFailureX733", 539),
          ("rectifierFailure", 114),
          ("rectifierHighVoltage", 115),
          ("rectifierLowFVoltage", 116),
          ("reducedLoggingCapability", 206),
          ("remoteAlarmInterface", 11),
          ("remoteNodeTransmissionError", 25),
          ("remoteNodeTransmissionErrorX733", 540),
          ("replaceableUnitMissing", 62),
          ("replaceableUnitProblem", 69),
          ("replaceableUnitTypeMismatch", 63),
          ("resourceAtOrNearingCapacity", 541),
          ("responseTimeExecessive", 542),
          ("retransmissionRateExcessive", 543),
          ("routingFailure", 26),
          ("sfwrDownloadFailure", 156),
          ("sfwrEnvironmentProblem", 155),
          ("signalLabelMismatch", 15),
          ("signalQualityEvaluationFailure", 79),
          ("smoke", 132),
          ("softwareError", 163),
          ("softwareErrorX733", 544),
          ("softwareProgramAbnormallyTerminated", 545),
          ("softwareProgramError", 546),
          ("storageCapacityProblem", 151),
          ("storageCapacityProblemX733", 547),
          ("synchronizationSourceMismatch", 64),
          ("systemResourcesOverload", 207),
          ("temperatureUnacceptable", 548),
          ("terminalProblem", 65),
          ("thresholdCrossed", 549),
          ("timeoutExpired", 164),
          ("timingProblem", 66),
          ("timingProblemX733", 550),
          ("toxicGas", 133),
          ("toxicLeakDetected", 551),
          ("tranceiverFailure", 80),
          ("transmissionError", 10),
          ("transmitFailure", 18),
          ("transmitFailureX733", 552),
          ("transmiterFailure", 553),
          ("transmitterFailure", 67),
          ("trunkCardProblem", 68),
          ("unauthorizedAccessAttempt", 614),
          ("unavailable", 14),
          ("underlayingResourceUnavailable", 165),
          ("underlyingResourceUnavailable", 554),
          ("unexpectedInformation", 615),
          ("ventilationsSystemFailure", 117),
          ("versionMismatch", 166),
          ("versionMismatchX733", 555))
    )



class IANAItuEventType(Integer32, TextualConvention):
    status = "current"
    subtypeSpec = Integer32.subtypeSpec
    subtypeSpec += ConstraintsUnion(
        SingleValueConstraint(
            *(1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11)
        )
    )
    namedValues = NamedValues(
        *(("communicationsAlarm", 2),
          ("environmentalAlarm", 6),
          ("equipmentAlarm", 5),
          ("integrityViolation", 7),
          ("operationalViolation", 8),
          ("other", 1),
          ("physicalViolation", 9),
          ("processingErrorAlarm", 4),
          ("qualityOfServiceAlarm", 3),
          ("securityServiceOrMechanismViolation", 10),
          ("timeDomainViolation", 11))
    )



# MIB Managed Objects in the order of their OIDs


# Managed Objects groups


# Notification objects


# Notifications groups


# Agent capabilities


# Module compliance


# Export all MIB objects to the MIB builder

mibBuilder.exportSymbols(
    "IANA-ITU-ALARM-TC-MIB",
    **{"IANAItuProbableCause": IANAItuProbableCause,
       "IANAItuEventType": IANAItuEventType,
       "ianaItuAlarmNumbers": ianaItuAlarmNumbers}
)
