version: '3.8'
services:
  web:
    build: ..
    image: mibs-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
