name: Remote image test

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  run-and-test:
    name: Pull image, run container, test HTTP/HTTPS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for repo context)
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image from GHCR
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/mibs.pysnmp.com:master
          echo "Pulling $IMAGE"
          docker pull $IMAGE

      - name: Run container
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/mibs.pysnmp.com:master
          docker rm -f mibs-test || true
          docker run -d --name mibs-test -p 8080:80 -p 8443:443 $IMAGE
          echo "Waiting for container to become healthy..."
          sleep 5

      - name: Test HTTP (port 8080)
        run: |
          set -e
          for i in $(seq 1 15); do
            if curl -sS -I http://localhost:8080 >/dev/null 2>&1; then
              echo "HTTP is responding"
              break
            fi
            echo "waiting for http... ($i)"
            sleep 1
          done

      - name: Test HTTPS (port 8443)
        run: |
          set -e
          for i in $(seq 1 15); do
            if curl -k -sS -I https://localhost:8443 >/dev/null 2>&1; then
              echo "HTTPS is responding"
              break
            fi
            echo "waiting for https... ($i)"
            sleep 1
          done

      - name: Show certificate info
        run: |
          echo | openssl s_client -connect localhost:8443 -servername mibs.pysnmp.com 2>/dev/null | openssl x509 -noout -subject -issuer -dates || true

      - name: Show nginx logs
        run: docker logs --tail 200 mibs-test || true

      - name: Cleanup
        if: always()
        run: |
          docker rm -f mibs-test || true
